/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package local.ci.first;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public int calc(int n) {
        return 0;
    }
}
